#!/bin/bash
# fagents-tty setup -- per-project installer.
#
# Usage:
#   bash setup.sh                          # install in current dir, project_name = basename
#   bash setup.sh --project <name>         # explicit project name
#   bash setup.sh --force                  # override registry slot conflict
#   bash setup.sh --update                 # refresh bin scripts + launchers + skill (idempotent)
#   bash setup.sh --agents <comma-list>    # override default launcher list (default: claude,codex)
#   bash setup.sh --no-launchers           # skip launcher install
#   bash setup.sh --no-skill               # skip project-local skill install
#
# Creates <project>/.fagents-tty/{bin,sessions,config,.gitignore},
# launcher scripts (./launch-<agent> for each --agents entry),
# and per-project skills at <project>/.{claude,codex}/skills/fagents-tty/SKILL.md.
# Does NOT modify .claude/settings.json or .codex/hooks.json. Does NOT install
# any skill globally under ~/.claude/skills/ or ~/.codex/skills/.

set -euo pipefail

# Private-by-default for everything this script creates. 0700 dirs, 0600 files.
# umask only applies to NEW paths; explicit chmod calls below handle the case
# where a path already exists with looser permissions.
umask 077

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
PROJECT_DIR="$(pwd -P)"
FAGENTS_TTY_DIR="$PROJECT_DIR/.fagents-tty"
REGISTRY_ROOT="${FAGENTS_TTY_REGISTRY_DIR:-$HOME/.fagents-tty/registry}"

PROJECT_NAME=""
FORCE=""
UPDATE=""
AGENTS_RAW=""
NO_LAUNCHERS=""
NO_SKILL=""

NAME_RE='^[A-Za-z0-9_][A-Za-z0-9_-]*$'

# ── Helpers ──

validate_name() {
    local name="$1"
    [ -z "$name" ] && return 1
    [[ "$name" =~ $NAME_RE ]]
}

# Parse a comma-separated --agents value into the AGENTS_ARR global. Rejects
# empty / leading-comma / trailing-comma / double-comma BEFORE splitting,
# because `IFS=',' read -ra` silently drops trailing empty fields and would
# otherwise let "claude," through. Inline (not a function) so an exit 1 here
# kills setup.sh directly without a subshell swallowing the rc; also avoids
# bash 4+ mapfile (macOS ships bash 3.2).
populate_agents_arr_from_raw() {
    local raw="$1" agent
    [ -z "$raw" ] && { echo "invalid --agents value (empty)" >&2; exit 1; }
    case "$raw" in
        ,*|*,|*,,*)
            echo "invalid --agents value '$raw' (empty entry)" >&2
            exit 1
            ;;
    esac
    AGENTS_ARR=()
    local IFS=','
    local -a tmp
    read -ra tmp <<< "$raw"
    for agent in "${tmp[@]}"; do
        validate_name "$agent" || { echo "invalid --agents entry '$agent'" >&2; exit 1; }
        AGENTS_ARR+=("$agent")
    done
}

# Write a fresh smart launcher for <agent> at <path>.
# The launcher registers in tandem (.tandem/) and fagents-tty (.fagents-tty/)
# if either is installed, then exec's the named CLI with all args.
write_fresh_launcher() {
    local agent="$1" path="$2"
    cat > "$path" <<EOF
#!/bin/bash
# Auto-generated by fagents-tty setup.sh. Registers in any installed toolkit
# (.tandem/ and/or .fagents-tty/) before exec'ing the CLI. Edit the exec line
# below if your CLI binary is not named "$agent".
ROOT="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
[ -x "\$ROOT/.tandem/bin/handoff.sh" ] && bash "\$ROOT/.tandem/bin/handoff.sh" register $agent
[ -x "\$ROOT/.fagents-tty/bin/comms.sh" ] && bash "\$ROOT/.fagents-tty/bin/comms.sh" register $agent
exec $agent "\$@"
EOF
    chmod 0700 "$path"
}

# Amend an existing launcher in place: insert the fagents-tty register line
# immediately before the first `exec` line. Idempotent (grep skip on second run).
# Refuses to amend if the launcher lacks `ROOT=` or `exec `; in that case prints
# manual instructions and exits 0 (non-blocking warning).
amend_existing_launcher() {
    local agent="$1" path="$2"
    # The $ROOT inside single quotes is INTENTIONAL: this string is inserted
    # verbatim into the user's launcher, where $ROOT is the launcher's own
    # variable. Only the trailing $agent should be expanded here.
    # shellcheck disable=SC2016
    local register_line='[ -x "$ROOT/.fagents-tty/bin/comms.sh" ] && bash "$ROOT/.fagents-tty/bin/comms.sh" register '"$agent"

    if grep -qF "$register_line" "$path"; then
        echo "  $path already includes fagents-tty register for $agent; skipping"
        return 0
    fi
    if ! grep -q '^ROOT=' "$path"; then
        echo "  WARN: $path does not define 'ROOT='; refusing to amend." >&2
        echo "        Add this line yourself before any 'exec' line:" >&2
        echo "          $register_line" >&2
        return 0
    fi
    if ! grep -q '^exec ' "$path"; then
        echo "  WARN: $path has no 'exec' line; refusing to amend." >&2
        echo "        Add this line yourself before any 'exec' line:" >&2
        echo "          $register_line" >&2
        return 0
    fi

    local tmpfile
    tmpfile=$(mktemp) || { echo "ERROR: mktemp failed (amend)" >&2; exit 1; }
    local awk_rc=0
    awk -v register="$register_line" '
        !inserted && /^exec / { print register; inserted=1 }
        { print }
        END { if (!inserted) exit 2 }
    ' "$path" > "$tmpfile" || awk_rc=$?

    if [ "$awk_rc" -eq 2 ]; then
        rm -f "$tmpfile"
        echo "  WARN: $path has no exec line (awk path); refusing to amend." >&2
        return 0
    fi
    if [ "$awk_rc" -ne 0 ]; then
        rm -f "$tmpfile"
        echo "ERROR: awk failed amending $path (rc=$awk_rc)" >&2
        exit "$awk_rc"
    fi
    mv "$tmpfile" "$path"
    chmod 0700 "$path"
    echo "  Amended $path: inserted fagents-tty register line before 'exec'"
}

install_launcher() {
    local agent="$1"
    local path="$PROJECT_DIR/launch-$agent"
    if [ -f "$path" ]; then
        amend_existing_launcher "$agent" "$path"
    else
        write_fresh_launcher "$agent" "$path"
        echo "  Created $path"
    fi
}

install_project_skill() {
    local tool="$1"
    local skill_dir="$PROJECT_DIR/.${tool}/skills/fagents-tty"
    mkdir -p "$skill_dir"
    # Explicit chmod is REQUIRED, not redundant: umask only applies to NEW
    # paths; `mkdir -p` does not tighten an existing permissive directory,
    # and `cp` over an existing file preserves the destination's mode.
    chmod 0700 "$skill_dir"
    cp "$SCRIPT_DIR/skill/SKILL.md" "$skill_dir/SKILL.md"
    chmod 0600 "$skill_dir/SKILL.md"
    echo "  Installed $tool skill: .${tool}/skills/fagents-tty/"
}

# Single source of truth for the launcher + skill install loop. Called from
# both the fresh-install path and `--update` so the two stay in sync.
install_launchers_and_skills() {
    if [ -z "$NO_LAUNCHERS" ]; then
        echo "Launchers:"
        local agent
        for agent in "${AGENTS_ARR[@]}"; do
            install_launcher "$agent"
        done
    fi
    if [ -z "$NO_SKILL" ]; then
        echo "Skills:"
        install_project_skill claude
        install_project_skill codex
    fi
}

# ── Arg parsing ──

while [ $# -gt 0 ]; do
    case "$1" in
        --project)
            PROJECT_NAME="${2:-}"
            [ -z "$PROJECT_NAME" ] && { echo "--project requires a value" >&2; exit 1; }
            shift 2
            ;;
        --force) FORCE=1; shift ;;
        --update) UPDATE=1; shift ;;
        --agents)
            AGENTS_RAW="${2:-}"
            [ -z "$AGENTS_RAW" ] && { echo "--agents requires a value" >&2; exit 1; }
            shift 2
            ;;
        --no-launchers) NO_LAUNCHERS=1; shift ;;
        --no-skill) NO_SKILL=1; shift ;;
        --help|-h)
            echo "Usage: bash setup.sh [--project <name>] [--force] [--update] [--agents <list>] [--no-launchers] [--no-skill]"
            exit 0
            ;;
        *) echo "Unknown arg: $1" >&2; exit 1 ;;
    esac
done

[ -z "$PROJECT_NAME" ] && PROJECT_NAME=$(basename "$PROJECT_DIR")
validate_name "$PROJECT_NAME" || { echo "ERROR: invalid project name '$PROJECT_NAME' (must match $NAME_RE)" >&2; exit 1; }

# Default agents: claude + codex (matches tandem). Override via --agents.
declare -a AGENTS_ARR
if [ -n "$AGENTS_RAW" ]; then
    populate_agents_arr_from_raw "$AGENTS_RAW"
else
    AGENTS_ARR=(claude codex)
fi

echo "=== fagents-tty setup ==="
echo "Project: $PROJECT_NAME"
echo "Directory: $PROJECT_DIR"
if [ -z "$NO_LAUNCHERS" ]; then
    echo "Launchers: ${AGENTS_ARR[*]}"
fi
echo ""

# ── Update mode: refresh bin scripts + launchers + skill (idempotent) ──

if [ -n "$UPDATE" ]; then
    if [ ! -d "$FAGENTS_TTY_DIR/bin" ]; then
        echo "ERROR: $FAGENTS_TTY_DIR/bin not found; run setup.sh without --update first" >&2
        exit 1
    fi
    cp "$SCRIPT_DIR/bin/comms.sh" "$FAGENTS_TTY_DIR/bin/comms.sh"
    cp "$SCRIPT_DIR/bin/wake.sh" "$FAGENTS_TTY_DIR/bin/wake.sh"
    chmod +x "$FAGENTS_TTY_DIR/bin/comms.sh" "$FAGENTS_TTY_DIR/bin/wake.sh"
    echo "Refreshed .fagents-tty/bin/"
    install_launchers_and_skills
    exit 0
fi

# ── Fresh install path ──

# Path conflict check
REGISTRY_PROJECT_DIR="$REGISTRY_ROOT/$PROJECT_NAME"
PATH_SIDECAR="$REGISTRY_PROJECT_DIR/.path"
if [ -f "$PATH_SIDECAR" ]; then
    EXISTING=$(cat "$PATH_SIDECAR" 2>/dev/null || true)
    if [ "$EXISTING" != "$PROJECT_DIR" ]; then
        if [ -z "$FORCE" ]; then
            echo "ERROR: project name '$PROJECT_NAME' is registered to '$EXISTING'." >&2
            echo "  Re-run with --force to take over, or pick a different --project name." >&2
            exit 1
        fi
        rm -rf "$REGISTRY_PROJECT_DIR"
        echo "Forced removal of previous registry: $EXISTING"
    fi
fi

# Claim the registry slot for this project NOW (writes .path), closing the
# gap between forced takeover (or fresh install) and first `register`.
mkdir -p "$REGISTRY_PROJECT_DIR"
printf '%s' "$PROJECT_DIR" > "$PATH_SIDECAR"

# Per-project install
mkdir -p "$FAGENTS_TTY_DIR/bin" "$FAGENTS_TTY_DIR/sessions"
cp "$SCRIPT_DIR/bin/comms.sh" "$FAGENTS_TTY_DIR/bin/comms.sh"
cp "$SCRIPT_DIR/bin/wake.sh" "$FAGENTS_TTY_DIR/bin/wake.sh"
chmod +x "$FAGENTS_TTY_DIR/bin/comms.sh" "$FAGENTS_TTY_DIR/bin/wake.sh"

if [ ! -f "$FAGENTS_TTY_DIR/config" ]; then
    printf 'project_name=%s\n' "$PROJECT_NAME" > "$FAGENTS_TTY_DIR/config"
fi

cat > "$FAGENTS_TTY_DIR/.gitignore" << 'EOF'
*
!.gitignore
!bin/
!bin/**
EOF

echo "Created $FAGENTS_TTY_DIR/"

install_launchers_and_skills

echo ""
echo "=== Setup complete ==="
echo ""
echo "Next steps:"
if [ -z "$NO_LAUNCHERS" ]; then
    echo "  1. Start your agent via the launcher (registers TTY automatically):"
    printf '       ./launch-%s\n' "${AGENTS_ARR[@]}"
    echo "  2. List who else is reachable:"
    echo "       bash .fagents-tty/bin/comms.sh ls"
    echo "  3. Send a msg:"
    echo "       bash .fagents-tty/bin/comms.sh msg <project>:<agent> \"your message\""
else
    echo "  1. Start your agent."
    echo "  2. Register manually:"
    echo "       bash .fagents-tty/bin/comms.sh register <agent-name>"
    echo "  3. Send / receive via comms.sh msg / ls."
fi
