#!/bin/bash
# fagents-tty setup -- per-project installer.
#
# v2 model: project name == directory basename. No --project flag, no
# config file, no global registry. State lives in <project>/.fagents-tty/.
#
# Usage:
#   bash setup.sh                          # install in current dir (basename = project name)
#   bash setup.sh --update                 # refresh bin scripts + launchers + skill (idempotent)
#   bash setup.sh --agents <comma-list>    # override default launcher list (default: claude,codex)
#   bash setup.sh --no-launchers           # skip launcher install
#   bash setup.sh --no-skill               # skip per-project skill install
#
# Creates:
#   <project>/.fagents-tty/{bin,.gitignore}
#   <project>/launch-<agent>   (one per --agents entry; existing launchers are amended via awk)
#   <project>/.{claude,codex}/skills/fagents-tty/SKILL.md
# Does NOT modify .claude/settings.json or .codex/hooks.json.

set -euo pipefail

umask 077

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
PROJECT_DIR="$(pwd -P)"
FAGENTS_TTY_DIR="$PROJECT_DIR/.fagents-tty"

UPDATE=""
AGENTS_RAW=""
NO_LAUNCHERS=""
NO_SKILL=""

NAME_RE='^[A-Za-z0-9_][A-Za-z0-9_-]*$'

# -- Helpers --

validate_name() {
    local name="$1"
    [ -z "$name" ] && return 1
    [[ "$name" =~ $NAME_RE ]]
}

populate_agents_arr_from_raw() {
    local raw="$1" agent
    [ -z "$raw" ] && { echo "invalid --agents value (empty)" >&2; exit 1; }
    case "$raw" in
        ,*|*,|*,,*)
            echo "invalid --agents value '$raw' (empty entry)" >&2
            exit 1
            ;;
    esac
    AGENTS_ARR=()
    local IFS=','
    local -a tmp
    read -ra tmp <<< "$raw"
    for agent in "${tmp[@]}"; do
        validate_name "$agent" || { echo "invalid --agents entry '$agent'" >&2; exit 1; }
        AGENTS_ARR+=("$agent")
    done
}

write_fresh_launcher() {
    local agent="$1" path="$2"
    cat > "$path" <<EOF
#!/bin/bash
# Auto-generated by fagents-tty setup.sh. Registers in any installed toolkit
# (.tandem/ and/or .fagents-tty/) before exec'ing the CLI. Edit the exec line
# below if your CLI binary is not named "$agent".
ROOT="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
[ -x "\$ROOT/.tandem/bin/handoff.sh" ] && bash "\$ROOT/.tandem/bin/handoff.sh" register $agent
[ -x "\$ROOT/.fagents-tty/bin/comms.sh" ] && bash "\$ROOT/.fagents-tty/bin/comms.sh" register $agent
exec $agent "\$@"
EOF
    chmod 0700 "$path"
}

amend_existing_launcher() {
    local agent="$1" path="$2"
    # shellcheck disable=SC2016
    local register_line='[ -x "$ROOT/.fagents-tty/bin/comms.sh" ] && bash "$ROOT/.fagents-tty/bin/comms.sh" register '"$agent"

    if grep -qF "$register_line" "$path"; then
        echo "  $path already includes fagents-tty register for $agent; skipping"
        return 0
    fi
    if ! grep -q '^ROOT=' "$path"; then
        echo "  WARN: $path does not define 'ROOT='; refusing to amend." >&2
        echo "        Add this line yourself before any 'exec' line:" >&2
        echo "          $register_line" >&2
        return 0
    fi
    if ! grep -q '^exec ' "$path"; then
        echo "  WARN: $path has no 'exec' line; refusing to amend." >&2
        echo "        Add this line yourself before any 'exec' line:" >&2
        echo "          $register_line" >&2
        return 0
    fi

    local tmpfile
    tmpfile=$(mktemp) || { echo "ERROR: mktemp failed (amend)" >&2; exit 1; }
    local awk_rc=0
    awk -v register="$register_line" '
        !inserted && /^exec / { print register; inserted=1 }
        { print }
        END { if (!inserted) exit 2 }
    ' "$path" > "$tmpfile" || awk_rc=$?

    if [ "$awk_rc" -eq 2 ]; then
        rm -f "$tmpfile"
        echo "  WARN: $path has no exec line (awk path); refusing to amend." >&2
        return 0
    fi
    if [ "$awk_rc" -ne 0 ]; then
        rm -f "$tmpfile"
        echo "ERROR: awk failed amending $path (rc=$awk_rc)" >&2
        exit "$awk_rc"
    fi
    mv "$tmpfile" "$path"
    chmod 0700 "$path"
    echo "  Amended $path: inserted fagents-tty register line before 'exec'"
}

install_launcher() {
    local agent="$1"
    local path="$PROJECT_DIR/launch-$agent"
    if [ -f "$path" ]; then
        amend_existing_launcher "$agent" "$path"
    else
        write_fresh_launcher "$agent" "$path"
        echo "  Created $path"
    fi
}

install_project_skill() {
    local tool="$1"
    local skill_dir="$PROJECT_DIR/.${tool}/skills/fagents-tty"
    mkdir -p "$skill_dir"
    chmod 0700 "$skill_dir"
    cp "$SCRIPT_DIR/skill/SKILL.md" "$skill_dir/SKILL.md"
    chmod 0600 "$skill_dir/SKILL.md"
    echo "  Installed $tool skill: .${tool}/skills/fagents-tty/"
}

install_launchers_and_skills() {
    if [ -z "$NO_LAUNCHERS" ]; then
        echo "Launchers:"
        local agent
        for agent in "${AGENTS_ARR[@]}"; do
            install_launcher "$agent"
        done
    fi
    if [ -z "$NO_SKILL" ]; then
        echo "Skills:"
        install_project_skill claude
        install_project_skill codex
    fi
}

# v1.x cleanup: remove stale config file and sessions/ dir from a previous
# install. Idempotent. Prints a single line if anything was actually removed,
# so a fresh-on-v2 install stays quiet.
cleanup_v1x_remnants() {
    local removed=""
    if [ -f "$FAGENTS_TTY_DIR/config" ]; then
        rm -f "$FAGENTS_TTY_DIR/config"
        removed="config"
    fi
    if [ -d "$FAGENTS_TTY_DIR/sessions" ]; then
        rm -rf "$FAGENTS_TTY_DIR/sessions"
        removed="${removed:+$removed, }sessions/"
    fi
    if [ -n "$removed" ]; then
        echo "Removed stale v1.x files: $removed"
    fi
}

# Print a non-blocking notice if the v1.x global registry exists.
notice_global_v1x() {
    if [ -d "$HOME/.fagents-tty/registry" ]; then
        echo "Detected v1.x global registry at $HOME/.fagents-tty/registry/."
        echo "v2 stores everything per-project; you can 'rm -rf $HOME/.fagents-tty'"
        echo "once all your fagents-tty projects are migrated to v2."
    fi
}

# -- Arg parsing --

while [ $# -gt 0 ]; do
    case "$1" in
        --update) UPDATE=1; shift ;;
        --agents)
            AGENTS_RAW="${2:-}"
            [ -z "$AGENTS_RAW" ] && { echo "--agents requires a value" >&2; exit 1; }
            shift 2
            ;;
        --no-launchers) NO_LAUNCHERS=1; shift ;;
        --no-skill) NO_SKILL=1; shift ;;
        --help|-h)
            echo "Usage: bash setup.sh [--update] [--agents <list>] [--no-launchers] [--no-skill]"
            exit 0
            ;;
        *) echo "Unknown arg: $1" >&2; exit 1 ;;
    esac
done

PROJECT_NAME=$(basename "$PROJECT_DIR")
validate_name "$PROJECT_NAME" || { echo "ERROR: invalid project dirname '$PROJECT_NAME' (must match $NAME_RE)" >&2; exit 1; }

# Default agents: claude + codex (matches tandem). Override via --agents.
declare -a AGENTS_ARR
if [ -n "$AGENTS_RAW" ]; then
    populate_agents_arr_from_raw "$AGENTS_RAW"
else
    AGENTS_ARR=(claude codex)
fi

echo "=== fagents-tty setup ==="
echo "Project: $PROJECT_NAME"
echo "Directory: $PROJECT_DIR"
if [ -z "$NO_LAUNCHERS" ]; then
    echo "Launchers: ${AGENTS_ARR[*]}"
fi
echo ""

# -- Update mode: refresh bin scripts + launchers + skill (idempotent) --

if [ -n "$UPDATE" ]; then
    if [ ! -d "$FAGENTS_TTY_DIR/bin" ]; then
        echo "ERROR: $FAGENTS_TTY_DIR/bin not found; run setup.sh without --update first" >&2
        exit 1
    fi
    cp "$SCRIPT_DIR/bin/comms.sh" "$FAGENTS_TTY_DIR/bin/comms.sh"
    cp "$SCRIPT_DIR/bin/wake.sh" "$FAGENTS_TTY_DIR/bin/wake.sh"
    chmod +x "$FAGENTS_TTY_DIR/bin/comms.sh" "$FAGENTS_TTY_DIR/bin/wake.sh"
    echo "Refreshed .fagents-tty/bin/"
    cleanup_v1x_remnants
    install_launchers_and_skills
    notice_global_v1x
    exit 0
fi

# -- Fresh install path --

mkdir -p "$FAGENTS_TTY_DIR/bin"
cp "$SCRIPT_DIR/bin/comms.sh" "$FAGENTS_TTY_DIR/bin/comms.sh"
cp "$SCRIPT_DIR/bin/wake.sh" "$FAGENTS_TTY_DIR/bin/wake.sh"
chmod +x "$FAGENTS_TTY_DIR/bin/comms.sh" "$FAGENTS_TTY_DIR/bin/wake.sh"

cat > "$FAGENTS_TTY_DIR/.gitignore" << 'EOF'
*
!.gitignore
!bin/
!bin/**
EOF

echo "Created $FAGENTS_TTY_DIR/"

cleanup_v1x_remnants
install_launchers_and_skills
notice_global_v1x

echo ""
echo "=== Setup complete ==="
echo ""
echo "Next steps:"
if [ -z "$NO_LAUNCHERS" ]; then
    echo "  1. Start your agent via the launcher (registers TTY automatically):"
    printf '       ./launch-%s\n' "${AGENTS_ARR[@]}"
    echo "  2. See who else is reachable (sibling projects with .fagents-tty/):"
    echo "       bash .fagents-tty/bin/comms.sh ls"
    echo "  3. Send a msg:"
    echo "       bash .fagents-tty/bin/comms.sh msg <project>:<agent> \"your message\""
else
    echo "  1. Start your agent."
    echo "  2. Register manually:"
    echo "       bash .fagents-tty/bin/comms.sh register <agent-name>"
    echo "  3. Send / receive via comms.sh msg / ls."
fi
